services:
  - type: web
    name: bloodlink-ai-backend
    env: python
    region: oregon
    plan: free
    runtime: python3
    repo: "https://github.com/Nishanth8904/BloodLinkAi" # <-- REPLACE this with your GitHub repo URL
    branch: main
    path: ai
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --chdir ai --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        value: "https://reliable-conkies-5ef161.netlify.app"